version: '2.1'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 5000:5000

  account-service:
    build: account-service
    ports:
      - 6000:6000

  statistics-service:
    build: statistics-service
    ports:
      - 7000:7000

  notification-service:
    build: notification-service
    ports:
      - 8000:8000

  mongodb:
    build: mongodb
    ports:
      - 27017:27017
