security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: '123456'
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  servlet:
    context-path: /accounts
  port: 6000
